### ISSUE TITLE
Issues on Craft CMS 3.5

### ISSUE THREAD

**Issue by khalwat** [thejoshsmith/craft-prism-syntax-highlighting#10]
On Craft CMS 3.5, editing a Prism Syntax Highlighting field, and then saving it results in none of the changes being saved.

I've only tested this with the field embedded in a Matrix block.

**Comment by moacode** [comment]
Thanks for reporting! I’m planning a review of my plugins next weekend so
will hopefully have an update around then.

**Comment by Pautomagi** [comment]
Can confirm.
It will also delete existing info in fields and replace it with the handle of the field.

For me this was just a single field as a global.

**Comment by Djive** [comment]
prism-javascript.min.js?v=1598726154:1 Uncaught TypeError: Cannot read property 'class-name' of undefined
at prism-javascript.min.js?v=1598726154:1
(anonymous)    @    prism-javascript.min.js?v=1598726154:1

This error blocks Entry Preview  reload.. 
and other modals for choosing entries. and similar.. 
Or you cant do allmost anything in craft..

If MatrixMate is installed, i checked with MatrixMate developer and this  above is issue..

**Comment by Djive** [comment]
Josh, can you check this soon...

**Comment by moacode** [comment]
Hi @Djive, I've just been looking into this and (rather annoyingly) I can't seem to replicate. Could you let me know what version of Craft and the plugin you're running?

I'm running Craft 3.5.9 and 1.0.4 of the plugin.

**Comment by moacode** [comment]
@Djive ignore the above comment. I cleared my cache and I can now replicate!

**Comment by moacode** [comment]
This should be resolved in release 1.0.5. If not, feel free to reopen!

**Comment by Djive** [comment]
its happenign when used with other plugin installed MATRIXMATE

I cheked with Matrixmate developer mmikel and got same. cheked everything and told that its PRISM issue

**Comment by Djive** [comment]
ah. just seen now.. ..I cleared my cache and I can now replicate! >  everything OK :)  THX

**Comment by httpster** [comment]
I'm still experiencing this issue. My content saves initially, but any subsequent edits are not saved.

I am running 1.0.5 and my Prism fields are inside a Neo field.
